__`DIRECTIONS : Below are 100 Questions from Numpy Library. 
                Attempt all questions. 
                Difficulty may vary from Medium to High. 
                Solution Provided for Reference. 
                Estimated Time : 150 minutes Approx`__

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Print the numpy version and the configuration

In [6]:
print(np.__version__)
#np.show_config()

1.15.4


3. Create a null vector of size 10 

In [7]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array

In [8]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


5. How to get the documentation of the numpy add function? 

In [9]:
np.add?
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

6. Create a null vector of size 10 but the fifth value which is 1 

In [10]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [11]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last

In [12]:

Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [14]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix 

In [15]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values

In [16]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.61365141 0.88951693 0.6176225 ]
  [0.88758593 0.47803468 0.18007971]
  [0.65557449 0.15311363 0.05366351]]

 [[0.43678936 0.3517093  0.71467289]
  [0.40276511 0.74790064 0.04555016]
  [0.06788646 0.49947342 0.76133924]]

 [[0.16951802 0.35354357 0.89309574]
  [0.89135657 0.81687683 0.98632091]
  [0.838354   0.55663099 0.7362456 ]]]


13. Create a 10x10 array with random values and find the minimum and maximum values

In [17]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.004651989337777329 0.9924727385282875


14. Create a random vector of size 30 and find the mean value

In [19]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5781073366587897


15. Create a 2d array with 1 on the border and 0 inside

In [18]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [20]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? 

In [21]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [22]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [23]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?¶

In [24]:

print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function

In [25]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix 

In [26]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.57057351  0.2963645   1.05722888  0.25329577 -1.30763342]
 [-1.23070993 -0.98724688  1.73592198  1.20846714  1.44265085]
 [-0.39814115 -0.38456814 -1.61330613  1.25778494 -0.49496392]
 [ 1.41574023 -0.20719396 -0.53025759 -1.0425839  -0.06498526]
 [ 0.91068949 -0.82075827  0.72268898  0.5409008  -0.18881151]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [29]:

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [30]:

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [31]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. What is the output of the following script?

In [32]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal?

- Z**Z
- 2 << Z >> 2
- Z <- Z
- 1j*Z
- Z/1/1
- Z<Z>Z

28. What are the result of the following expressions?

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\10656309\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\10656309\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


29. How to round away from zero a float array ? 

In [35]:

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 5. -3. -4.  5. -4.  5. -2. -6.  6. -4.]


30. How to find common values between two arrays? 

In [36]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 3 4 7]


31. How to ignore all numpy warnings (not recommended)? 

In [38]:

defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

###########################################

_ = np.seterr(**defaults)

###########################################

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

32. Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)

33. How to get the dates of yesterday, today and tomorrow?

In [41]:

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2019-03-31
2019-04-01
2019-04-02


34. How to get all the dates corresponding to the month of July 2016?

In [40]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [42]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array using 5 different methods

In [43]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 3. 6. 2. 4. 0. 5. 0. 9. 1.]
[2. 3. 6. 2. 4. 0. 5. 0. 9. 1.]
[2. 3. 6. 2. 4. 0. 5. 0. 9. 1.]
[2 3 6 2 4 0 5 0 9 1]
[2. 3. 6. 2. 4. 0. 5. 0. 9. 1.]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [45]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [46]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [47]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it

In [48]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.01517579 0.02763631 0.11767194 0.70264866 0.70658115 0.72782122
 0.84666938 0.85809622 0.94653433 0.98412954]


41. How to sum a small array faster than np.sum?

In [49]:

Z = np.arange(10)
np.add.reduce(Z)

45


42. Consider two random array A and B, check if they are equal 

In [50]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


43. Make an array immutable (read-only) 

In [51]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [52]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.96039707 0.73493301 0.55076487 0.67041975 0.35299574 0.45767631
 0.84759835 0.85965771 0.56417259 0.63950853]
[0.86511278 1.2110669  0.92915714 1.09297549 0.71430583 0.76187944
 0.43929996 0.95147766 0.82187358 1.01849181]


45. Create random vector of size 10 and replace the maximum value by 0

In [53]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.44139231 0.22724201 0.5796971  0.         0.39931125 0.23685496
 0.73383218 0.10068079 0.13521236 0.57798343]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [54]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [55]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


3638.1636371179666


48. Print the minimum and maximum representable value for each numpy scalar type

In [56]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. How to print all the values of an array? 

In [57]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


50. How to find the closest value (to a given scalar) in a vector?

In [58]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

35


51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [59]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [60]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.61524717 0.47873611 0.40582534 0.42051175 0.22877956
  0.539152   0.63403529 0.68814565 0.50247804]
 [0.61524717 0.         0.60334461 0.82477219 0.77609141 0.64375944
  0.41887586 0.15734745 0.11219501 0.81802332]
 [0.47873611 0.60334461 0.         0.88213988 0.88666959 0.27775539
  0.8214822  0.72461561 0.71481632 0.96495055]
 [0.40582534 0.82477219 0.88213988 0.         0.07855905 0.63108407
  0.51351151 0.76202467 0.84849119 0.13725383]
 [0.42051175 0.77609141 0.88666959 0.07855905 0.         0.64921337
  0.44333024 0.70279855 0.79187395 0.08305334]
 [0.22877956 0.64375944 0.27775539 0.63108407 0.64921337 0.
  0.70482974 0.71400075 0.74078493 0.73125674]
 [0.539152   0.41887586 0.8214822  0.51351151 0.44333024 0.70482974
  0.         0.29402329 0.38973532 0.45481665]
 [0.63403529 0.15734745 0.72461561 0.76202467 0.70279855 0.71400075
  0.29402329 0.         0.0957256  0.7312636 ]
 [0.68814565 0.11219501 0.71481632 0.84849119 0.79187395 0.74078493
  0.38973532 0.09572

53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [61]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


54. How to read the following file?

In [62]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


55. What is the equivalent of enumerate for numpy arrays?

In [63]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


56. Generate a generic 2D Gaussian-like array

In [64]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

57. How to randomly place p elements in a 2D array?

In [65]:

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


58. Subtract the mean of each row of a matrix

In [66]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.07303394  0.3042888  -0.41348899  0.32688472 -0.10155632 -0.02008144
   0.13080284 -0.31965383 -0.2243647   0.24413498]
 [ 0.503839   -0.3119753   0.36893841 -0.30167328 -0.13419728  0.25210085
  -0.23054647  0.11630195 -0.36424272  0.10145484]
 [ 0.2746093   0.28688706  0.29278286  0.28136685 -0.42843565 -0.37712666
  -0.36872563  0.39570935 -0.03655981 -0.32050768]
 [-0.03900867 -0.14446231  0.1119949  -0.19937728  0.29944818 -0.20966579
  -0.05953648 -0.11974292 -0.10795889  0.46830925]
 [ 0.4259335  -0.10442951  0.0542317   0.00912007 -0.34582643 -0.24493223
   0.36984343 -0.15421407  0.36071371 -0.37044017]]


59. How to sort an array by the nth column?

In [67]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 9 3]
 [7 6 0]
 [3 9 9]]
[[7 6 0]
 [4 9 3]
 [3 9 9]]


60. How to tell if a given 2D array has null columns?

In [68]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


61. Find the nearest value from a given value in an array

In [69]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.49370245089387754


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 

In [70]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. Create an array class that has a name attribute

In [71]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [72]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution

np.add.at(Z, I, 1)
print(Z)

[1. 5. 2. 3. 5. 2. 4. 3. 2. 3.]
[1. 9. 3. 5. 9. 3. 7. 5. 3. 5.]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 

In [73]:

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [74]:

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


67. Considering a four dimensions array, how to get sum over the last two axis at once? 

In [75]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 45 55 77]
 [54 59 48 65]
 [35 56 36 57]]
[[58 45 55 77]
 [54 59 48 65]
 [35 56 36 57]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? 

In [76]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.4333173  0.59741776 0.60907249 0.57044495 0.29100933 0.501809
 0.70092296 0.38546076 0.4645611  0.71388619]
0    0.433317
1    0.597418
2    0.609072
3    0.570445
4    0.291009
5    0.501809
6    0.700923
7    0.385461
8    0.464561
9    0.713886
dtype: float64


69. How to get the diagonal of a dot product?

In [77]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.77335829, 1.50581573, 0.89928614, 0.59971907, 1.62056966])

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [78]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [79]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. How to swap two rows of an array?

In [80]:

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [81]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 37) ( 1, 45) ( 7, 78) ( 7, 86) (10, 21) (10, 59) (21, 59) (24, 29)
 (24, 44) (24, 69) (24, 87) (29, 87) (33, 51) (33, 80) (34, 55) (34, 60)
 (37, 45) (37, 58) (37, 73) (44, 49) (44, 69) (44, 78) (49, 78) (51, 80)
 (55, 60) (58, 73) (65, 79) (65, 89) (78, 86) (79, 89)]



74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? 

In [82]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


75. How to compute averages using a sliding window over an array?

In [83]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [84]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. How to negate a boolean, or to change the sign of a float inplace?

In [85]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.19549161,  0.43655806,  0.19979279,  0.4114682 ,  0.89950134,
       -0.32132351, -0.81313487, -0.00372492,  0.353763  ,  0.41286405,
       -0.22102857, -0.52864984, -0.6573906 , -0.30557687,  0.22980578,
        0.27129923, -0.09018067, -0.51744136,  0.74537999,  0.9748958 ,
       -0.60273055,  0.27677807,  0.29081484, -0.47283313, -0.62140388,
       -0.37229224,  0.02337537, -0.98023455,  0.23573753, -0.06742956,
        0.24674208,  0.88233561, -0.86444488, -0.593728  ,  0.91665424,
        0.04203488, -0.16046184,  0.73604343,  0.70279567, -0.7861626 ,
       -0.70843784, -0.85197892,  0.68084584, -0.8811715 ,  0.82491156,
       -0.51828911,  0.05281199,  0.04402603,  0.12040268,  0.86518161,
       -0.34831285,  0.85254308, -0.05048093,  0.47944982,  0.89600878,
       -0.7795205 ,  0.48922278,  0.73299676,  0.86735058, -0.46938933,
       -0.62645469,  0.89888248, -0.23556953, -0.70683715, -0.57640761,
        0.51886247,  0.37291214, -0.27981227, -0.73401726,  0.76

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [86]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 0.51362301 14.61338892 12.42736171  8.60911575 12.9479069   8.22835358
 15.0138936   4.06800886  7.49858853 11.15589857]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [87]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[18.67090251  2.46569295  3.90109104  7.37400555  6.05796095 11.10444204
  16.03984106  9.94327549  1.3115406   5.72567031]
 [ 6.43780051  6.71080884  1.5546131   5.03528842  3.19674994 10.01391759
   2.06891119  9.17973639  5.95115314  0.80207069]
 [ 7.83015735  0.25870906  4.55770042  3.47676723  3.986896    5.53787489
   6.69000214  4.59619307  0.39578829  6.82472358]
 [ 2.0107697   3.0366783   3.57431784  9.33708135  8.93058435  3.66876305
   0.93362181  2.86199971  1.43869363  6.08592629]
 [10.59717849  9.1813925  13.2701919   0.47091092  4.40416021  0.48024373
  13.97781965  1.59160321  9.55644259 15.37723139]
 [12.31884082  1.80349928  5.23443892  1.04130832  0.14621468  7.04808691
  11.08494967  6.00338472  1.72857622  7.31323878]
 [16.69197727  7.35479607  5.44653358  5.14134499  7.40265818 18.01930729
   9.10752079 17.01938049  8.3730376   3.49102278]
 [ 5.9123089   1.01310319  6.45479989  5.34900361  6.36182305  3.06117622
   6.01889543  2.13552955  2.02411123  8.79065961]



80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) 

In [88]:

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


[[0 4 3 5 4 6 4 1 8 1]
 [0 3 6 6 8 2 7 3 6 8]
 [8 3 2 3 8 9 1 5 0 3]
 [5 8 1 6 0 8 6 7 0 2]
 [0 3 8 0 6 4 7 6 6 2]
 [7 1 6 0 8 4 8 4 7 0]
 [4 6 8 2 8 4 6 5 4 6]
 [0 0 2 0 4 7 7 2 4 5]
 [8 6 2 3 2 8 7 3 5 1]
 [0 9 9 8 9 3 2 3 9 9]]
[[0 0 0 0 0]
 [0 0 4 3 5]
 [0 0 3 6 6]
 [0 8 3 2 3]
 [0 5 8 1 6]]


C:\Users\10656309\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.



81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

In [89]:

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]



82. Compute a matrix rank 

In [90]:

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


83. How to find the most frequent value in an array?

In [91]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [92]:

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 1 2]
   [0 4 2]
   [2 0 2]]

  [[1 2 2]
   [4 2 2]
   [0 2 1]]

  [[2 2 2]
   [2 2 3]
   [2 1 0]]

  [[2 2 2]
   [2 3 3]
   [1 0 4]]

  [[2 2 4]
   [3 3 2]
   [0 4 3]]

  [[2 4 0]
   [3 2 0]
   [4 3 2]]

  [[4 0 0]
   [2 0 3]
   [3 2 3]]

  [[0 0 1]
   [0 3 1]
   [2 3 3]]]


 [[[0 4 2]
   [2 0 2]
   [1 4 1]]

  [[4 2 2]
   [0 2 1]
   [4 1 4]]

  [[2 2 3]
   [2 1 0]
   [1 4 1]]

  [[2 3 3]
   [1 0 4]
   [4 1 3]]

  [[3 3 2]
   [0 4 3]
   [1 3 2]]

  [[3 2 0]
   [4 3 2]
   [3 2 2]]

  [[2 0 3]
   [3 2 3]
   [2 2 1]]

  [[0 3 1]
   [2 3 3]
   [2 1 2]]]


 [[[2 0 2]
   [1 4 1]
   [1 3 2]]

  [[0 2 1]
   [4 1 4]
   [3 2 1]]

  [[2 1 0]
   [1 4 1]
   [2 1 1]]

  [[1 0 4]
   [4 1 3]
   [1 1 0]]

  [[0 4 3]
   [1 3 2]
   [1 0 0]]

  [[4 3 2]
   [3 2 2]
   [0 0 2]]

  [[3 2 3]
   [2 2 1]
   [0 2 3]]

  [[2 3 3]
   [2 1 2]
   [2 3 4]]]


 [[[1 4 1]
   [1 3 2]
   [1 2 4]]

  [[4 1 4]
   [3 2 1]
   [2 4 3]]

  [[1 4 1]
   [2 1 1]
   [4 3 2]]

  [[4 1 3]
   [1 1 0]
   [3 2 4]]

  [[1 3 2]
   

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] 

In [93]:
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  4  6 11 10]
 [ 4  3 10 14 11]
 [ 6 10  6 42  8]
 [11 14 42  1 10]
 [10 11  8 10  7]]



86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 

In [94]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

In [95]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. How to implement the Game of Life using numpy arrays?

In [96]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

89. How to get the n largest values of an array

In [97]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9996 9999 9998 9995]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [98]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


91. How to create a record array from a regular array? 

In [99]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [104]:
x = np.random.rand(5)

%timeit np.power(x,3)

1.73 µs ± 70.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [105]:
%timeit x*x*x

1.13 µs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [106]:
%timeit np.einsum('i,i,i->i',x,x,x)

2.34 µs ± 371 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)



93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [107]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 4 5 6]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [108]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 1 2]
 [1 1 4]
 [3 1 1]
 [1 3 3]
 [4 0 4]
 [3 3 1]
 [2 1 1]
 [1 4 0]
 [1 1 3]
 [0 0 4]]
[[4 1 2]
 [1 1 4]
 [3 1 1]
 [1 3 3]
 [4 0 4]
 [3 3 1]
 [2 1 1]
 [1 4 0]
 [1 1 3]
 [0 0 4]]
[[4 1 2]
 [1 1 4]
 [3 1 1]
 [1 3 3]
 [4 0 4]
 [3 3 1]
 [2 1 1]
 [1 4 0]
 [1 1 3]
 [0 0 4]]


95. Convert a vector of ints into a matrix binary representation

In [109]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Alternate Method 

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 4]
 [1 1 3]
 [1 1 4]
 [1 3 3]
 [1 4 0]
 [2 1 1]
 [3 1 1]
 [3 3 1]
 [4 0 4]
 [4 1 2]]


96. Given a two dimensional array, how to extract unique rows?


In [110]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 1 1]]



97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function 

In [111]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.11176523, 0.01157689, 0.01829261, 0.01824942, 0.06492448,
        0.18005911, 0.05381149, 0.01369799, 0.0136777 , 0.12420485],
       [0.10576692, 0.01095557, 0.01731087, 0.01726999, 0.06144006,
        0.17039555, 0.05092349, 0.01296283, 0.01294363, 0.11753892],
       [0.46473787, 0.04813858, 0.07606364, 0.07588402, 0.26996646,
        0.74871485, 0.22375688, 0.05695845, 0.05687409, 0.5164638 ],
       [0.10480524, 0.01085596, 0.01715347, 0.01711297, 0.06088142,
        0.16884624, 0.05046047, 0.01284497, 0.01282595, 0.1164702 ],
       [0.10477851, 0.01085319, 0.0171491 , 0.0171086 , 0.06086589,
        0.16880317, 0.0504476 , 0.01284169, 0.01282267, 0.11644049],
       [0.49295843, 0.05106172, 0.0806825 , 0.08049197, 0.2863598 ,
        0.79417951, 0.2373442 , 0.06041717, 0.06032769, 0.54782534],
       [0.09464991, 0.00980405, 0.01549135, 0.01545477, 0.05498218,
        0.15248551, 0.045571  , 0.01160033, 0.01158315, 0.10518456],
       [0.19097516, 0.01978163, 0.0312569


98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples 


In [112]:

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [113]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[[2. 0. 1. 1.]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [114]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12747858  0.23610793]


-- ENDS HERE --